"""auto-vote

Revision ID: 49e16d3b3a5a
Revises: 4c1fe2b8a649
Create Date: 2026-05-29 12:48:31.533931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49e16d3b3a5a'
down_revision: Union[str, Sequence[str], None] = '4c1fe2b8a649'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table('votes',
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('post_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('user_id', 'post_id')
                    )
    
    # # ### commands auto generated by Alembic - please adjust! ###    
    # op.create_index(op.f('ix_posts_title'), 'posts', ['title'], unique=False)
    # op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    # # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table('votes')
    
    # # ### commands auto generated by Alembic - please adjust! ###
    # op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    # op.drop_index(op.f('ix_posts_title'), table_name='posts')
    # # ### end Alembic commands ###
